name: Synchronization issue
description: Neuron doesn't synchronize
title: '[Synchronization] **brief description**'
labels:
  - bug
assignees:
  - Keith-CY
body:
  - type: markdown
    attributes:
      value: |
        Please check if these issues help
        - [Synchronization doesnt' start](https://github.com/nervosnetwork/neuron/issues/2388)
        - [Transactions keep pending on Neuron v0.101.3](https://github.com/nervosnetwork/neuron/issues/2384)
        - [`Check for update` in settings doesn't work](https://github.com/nervosnetwork/neuron/issues/2372)

  - type: textarea
    id: detial
    validations:
      required: true
    attributes:
      label: Detail of the issue
      description: Elaborate on your issue in this field
      
  - type: markdown
    attributes:
      value: |

        ---
        ## Please add neuron logs if possible, they can be exported by `Menu -> Help -> Export Debug Information`

  - type: textarea
    id: bundled-ckb
    validations:
      required: false
    attributes:
      label: bundled-ckb.log
      render: shell
      
  - type: textarea
    id: main-log
    validations:
      required: false
    attributes:
      label: main.log
      render: shell

  - type: textarea
    id: status
    validations:
      required: false
    attributes:
      label: status.log
      render: shell

